package:
  name: lib_prep
  version: "1.1.2"

about:
  home: https://github.com/carlesperez94/lib_prep
  license: MIT
  license_file: LICENSE
  summary: Python package to analyse and prepare libraries of chemical compounds for molecular simulations.

source:
  path: ../

build:
  script: python -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python
    - numpy

  run:
    # Base dependencies
    - python
    - numpy
    - prody >=1.10.10
    - rdkit
    - pytest

test:
  imports:
    - lib_prep
  command:
    - python -m lib_prep.convert_sdfs2pdb.py -h
    - python -m lib_prep.FragmentTools.prepare_to_frag.py -h 
