name: Installation through setup.py
on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install numpy cython
    - name: Install via Pypi
      run: |
        python setup.py install
    - name: Test import 
      run: |
          mkdir test_pypi
          cd test_pypi
          python -m lib_prep.convert_sdfs2pdb -h
